version: '2'
services:
  web:
    build: .
    command: nodemon index.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: abraxas_task_admin
    ports:
      - "3307:3306"
